primeiro = int(input('Primeiro termo: '))
razao = int(input('Razão: '))
termo = primeiro
cont = 1
while cont <= 10:
    print('{} - '.format(termo), end=' ')
    termo = termo + razao
    cont += 1
mais = int(input('\nDeseja mostrar mais algum termo?'))
